---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/ubuntu-base
    tag: 'latest'

inputs:
  - name: page-source
  - name: ci-source
  - name: version

outputs:
  - name: site

run:
  path: ci-source/ci/landing/tasks/build.sh

